theme = "hugo-theme-m10c"
baseURL = 'https://dev.negtak.net/'
languageCode = 'en-us'
title = 'negtak'
publishDir = "docs"
canonifyurls = true
pagination = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[params]
  author = "negtak"
  description = "negtak's blog"
  menu_item_separator = " - "
  avatar = "avatar.jpg"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/negtak"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/ne9oll4"
  [[params.social]]
    icon = "instagram"
    name = "Instagram"
    url = "https://instagram.com/ne9tak"
  [[params.social]]
    icon = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/gen-takagaki/"
